### ISSUE TITLE
Benchmark about string draw

### ISSUE THREAD

**Issue by dabing1022** [jjkaufman/SwiftProcessing#100]
# Processing (Java)

I runned this code, and the framerate is stayed at 40-50 fps.
```java

public void setup() {
  size(800, 600, P2D);
  fill(0);
}
  
public void draw() {    
  background(255);
  for (int i = 0; i < 10000; i++) {
    float x = random(width);
    float y = random(height);
    text("HELLO", x, y);
  }
  
  pushStyle();
  textSize(32);
  fill(255, 0, 0);
  text(frameRate, 20, 40);
  popStyle();
}
```

![image](https://user-images.githubusercontent.com/1892303/132127586-94606e14-2967-4f88-8bde-8cd5c6b217af.png)

# SwiftProcessing

![image](https://user-images.githubusercontent.com/1892303/132127619-5c91b911-e8e7-419a-aa68-754d1bcd2d15.png)

```swift
import SwiftProcessing
import UIKit

class MySketch: Sketch, SketchDelegate{
    
    var attr: [NSAttributedString.Key: Any]?
    
    func setup() {
        appMode()
        fill(0)
        
        let paragraphStyle = NSMutableParagraphStyle()
        paragraphStyle.alignment = .left
        paragraphStyle.lineSpacing = CGFloat(37)
        
        let attributes: [NSAttributedString.Key: Any] = [
            .paragraphStyle: paragraphStyle,
            .font: UIFont(name: "HelveticaNeue-Thin", size: 32)!,
            .foregroundColor: UIColor.black,
            .strokeWidth: -1.0,
            .strokeColor:UIColor.black
        ]
        self.attr = attributes
    }
    
    func draw() {
        background(255)
        for _ in 0..<10000 {
            let x = random(width)
            let y = random(height)
//            text("Hello", x, y)
                        
            // very slowly when use attributes
            "Hello".draw(with: CGRect(x: x, y: y, width: CGFloat(width), height: CGFloat(height)), options: .usesLineFragmentOrigin, attributes: attr, context: nil)
            // it seems better when attributes is nil
//            "Hello".draw(with: CGRect(x: x, y: y, width: CGFloat(width), height: CGFloat(height)), options: .usesLineFragmentOrigin, attributes: nil, context: nil)
        }
    }
    
}

```

String draw is very slowly, when I tried to change attributes to nil, it becomed very quick.

Is there any way to optimize this?

**Comment by masoodkamandy** [comment]
Thank you for this feedback. This is great information!

There are a couple of things to be aware of when you make a comparison like this.

Your Processing sketch is 800, 600 pixels and you are using P2D, which is GPU rendering. SwiftProcessing does not have GPU rendering at this point. It is entirely CPU driven.

The CPU version of your code using the default renderer drops to about 10 fps in Processing.

You're also comparing a 800x600 pixel sketch in Processing with a 1366x1024 *point* sketch in Processing. The iPad pro pushes 2732-by-2048-pixels resolution at 264 pixels per inch every frame.

If I take your Processing sketch and up the resolution to 2732x2048 and use CPU renderer, I get 7 frames per second.

Now we can make a comparison.

I tested your code against a normal SwiftProcessing version of this code:

```
import SwiftProcessing
import UIKit

class MySketch: Sketch, SketchDelegate{

    func setup() {
        background(255)

    }

    func draw() {
        background(255)
        for i in 0..<10000 {
            textSize(12)
            let x = random(width)
            let y = random(height)
            text("HELLO", x, y)
        }

        pushStyle()
        textSize(32)
        fill(255, 0, 0)
        text("\(frameRate)", 20, 40)
        popStyle()
    }

}
```

You are absolutely correct that we see a huge performance boost with nil attributes! This may require a refactor of the text function, but this is very welcome information!

Thanks again.

**Comment by jjkaufman** [comment]
I've been dealing with a similar problem in the experimental SwiftUI branch where Text is surprisingly slow. I am experimenting with the idea of caching text based on the various attributes and trying to save the expensive part to memory with some time to live

**Comment by dabing1022** [comment]
> Thank you for this feedback. This is great information!
> 
> There are a couple of things to be aware of when you make a comparison like this.
> 
> Your Processing sketch is 800x600 pixels and you are using P2D, which is GPU rendering. SwiftProcessing does not have GPU rendering at this point. It is entirely CPU driven.
> 
> The CPU version of your code using the default renderer drops to about 10 fps in Processing.
> 
> You're also comparing a 800x600 pixel sketch in Processing with a 1366x1024 _point_ sketch in Processing. The iPad pro pushes 2732-by-2048-pixels resolution at 264 pixels per inch every frame.
> 
> If I take your Processing sketch and up the resolution to 2732x2048 and use CPU renderer, I get 7 frames per second.
> 
> Now we can make a comparison.
> 
> I tested your code against a normal SwiftProcessing version of this code:
> 
> ```swift
> import SwiftProcessing
> import UIKit
> 
> class MySketch: Sketch, SketchDelegate{
> 
>     func setup() {
>         background(255)
> 
>     }
> 
>     func draw() {
>         background(255)
>         for i in 0..<10000 {
>             textSize(12)
>             let x = random(width)
>             let y = random(height)
>             text("HELLO", x, y)
>         }
> 
>         pushStyle()
>         textSize(32)
>         fill(255, 0, 0)
>         text("\(frameRate)", 20, 40) // frameRate needs to be implemented. The breadcrumbs for it are in the source code.
>         popStyle()
>     }
> 
> }
> ```
> 
> You are absolutely correct that we see a huge performance boost with nil attributes!
> 
> This may require a refactor of the text function, but this is very welcome information!
> 
> Thanks again.

I digged the `text` function in `SketchTypography.swift`，

```swift
func text<X: Numeric, Y: Numeric, X2: Numeric, Y2: Numeric>(_ string: String, _ x: X, _ y: Y, _ x2: X2?, _ y2: Y2?) {
        let cg_x, cg_y: CGFloat
        let cg_x2, cg_y2: CGFloat?
        cg_x = x.convert()
        cg_y = y.convert()
        cg_x2 = x2?.convert()
        cg_y2 = y2?.convert()
        
        let paragraphStyle = NSMutableParagraphStyle()
        
        var align: NSTextAlignment!
        switch settings.textAlign {
        case .left:
            align = .left
        case .right:
            align = .right
        case .center:
            align = .center
        }
        paragraphStyle.alignment = align
        paragraphStyle.lineSpacing = CGFloat(settings.textLeading)
        
        
        let attributes: [NSAttributedString.Key: Any] = [
            .paragraphStyle: paragraphStyle,
            .font: UIFont(name: settings.textFont, size: CGFloat(settings.textSize))!,
            .foregroundColor: settings.fill.uiColor(),
            .strokeWidth: -settings.strokeWeight,
            .strokeColor: settings.stroke.uiColor()
        ]
        
        if cg_x2 == nil {
            string.draw(at: CGPoint(x: cg_x, y: cg_y), withAttributes: attributes)
        } else {
            string.draw(with: CGRect(x: cg_x, y: cg_y, width: (cg_x2 != nil) ? cg_x2! : CGFloat(width), height: (cg_y2 != nil) ? cg_y2! : CGFloat(height)), options: .usesLineFragmentOrigin, attributes: attributes, context: nil)
        }
    }
```

In essence, the draw method of string is called last, and attributes are also brought. Same as my demo lol 😂

**Comment by masoodkamandy** [comment]
I wonder if it's less performant than your demo because we're re-initializing the attributes and style every frame, whereas you're creating it once in `setup()`.

**Comment by dabing1022** [comment]
I put attributes into the setup function to test whether the performance is improved. Indeed, it would be worse to build a new attribute every frame
