### ISSUE TITLE
Touch functions do not have access to graphics context 

### ISSUE THREAD

**Issue by jjkaufman** [jjkaufman/SwiftProcessing#106]
relevant slack thread https://swiftprocessing.slack.com/archives/CQAHER45T/p1631236387028500

If a sketch implements a touchEnded function, calls requiring a graphics context do not mutate the canvas. We need to adjust the logic to make sure the code executes next frame

**Comment by masoodkamandy** [comment]
API users have full access to the graphics context from touch. The example code provided to us was trying to call a shape function but was then immediately overwriting it with the `background()` method in the draw loop.

This was user error and is not an issue with the API.
