### ISSUE TITLE
draw() with background in setup() doesn't work properly

### ISSUE THREAD

**Issue by briancpark** [jjkaufman/SwiftProcessing#19]
The draw() function has a bug where it doesn't permanently leave drawings if background() is in setup(). It's as if background was under draw(). Here is example code where I found the bug. 

```swift
var t = CGFloat(0.0)

func setup() {
    background(0, 0, 0)
}

func draw() {
    stroke(255, 255, 255)
    strokeWeight(5)
    translate(width/2, height/2)
    point(t, t)
    t += 1
}
```
And [here](https://editor.p5js.org/briancpark/sketches/LZXKEf5S4) is a p5.js version of the same code that properly works.

**Comment by jjkaufman** [comment]
Thanks for documenting this issue @briancpark 

Indeed, this is a big one. It'd be very hard to create a drawing app with this current bug present. 👨‍🎨

Should be resolvable by saving the Core Graphics context as an image at the end of the Sketch draw function and painting the last frames image at the start of the Sketch draw function.

**Comment by jjkaufman** [comment]
investigating a more simple solution. 

        backgroundColor = nil
        clearsContextBeforeDrawing = false

https://developer.apple.com/documentation/uikit/uiview/1622449-clearscontextbeforedrawing
