### ISSUE TITLE
Ok, I’m very new to this! Is this a Swift repo for iPad? If yes then....

### ISSUE THREAD

**Issue by Yashsinh** [jjkaufman/SwiftProcessing#53]
Hey guys! I am new to Swift 5.1. Can anyone send me an iPad code for turning on the camera and then Hello World written under it? Please help me
Thank you!

**Comment by jjkaufman** [comment]
Hi @Yashsinh 

Here is a hello world camera sketch example to get you started. You will have to launch it from xCode to your real iPad. The camera code cannot run in the simulator. 


```
import Foundation
import SwiftProcessing

class MySketch: Sketch,SketchDelegate {
    var camera: Camera!

    func setup() {
        self.camera = createCamera(FRONT)
        camera.setResolution(MEDIUM)
        self.camera.hide()
    }

    func draw() {
        var img = self.camera.get()
        image(img, 0, 0, width, height)
        textAlign(CENTER)
        textSize(60)
        text("hello world!", 0, height * 0.7, width)
    }
}
```



We are working on more examples for the website right now so stay tuned!
